# Generated by Django 6.1 on 2026-09-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
    ]
